# Generated by Django 2.2 on 2019-07-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=255)),
                ('social_security_number', models.CharField(max_length=255)),
                ('citizenship', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=255)),
                ('number_of_dependents', models.CharField(max_length=255)),
                ('employment_status', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('investment_experience', models.CharField(max_length=255)),
                ('employer_name', models.CharField(max_length=255)),
                ('trade_options', models.CharField(max_length=255)),
                ('risk_level', models.CharField(max_length=255)),
                ('strategy', models.CharField(max_length=255)),
                ('term_period', models.CharField(max_length=255)),
                ('fund1', models.CharField(max_length=255)),
                ('fund1_percentage', models.CharField(max_length=255)),
                ('fund1_prospectus', models.CharField(max_length=255)),
                ('fund2', models.CharField(max_length=255)),
                ('fund2_percentage', models.CharField(max_length=255)),
                ('fund2_prospectus', models.CharField(max_length=255)),
                ('fund3', models.CharField(max_length=255)),
                ('fund3_percentage', models.CharField(max_length=255)),
                ('fund3_prospectus', models.CharField(max_length=255)),
                ('cash', models.CharField(max_length=255)),
                ('cash_percentage', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
